import Foundation

var usesTraditionalChinese: Bool { UserDefaults.standard.string(forKey: "uiLanguage") == "zh-Hant" }

func L(_ key: String) -> String { usesTraditionalChinese ? key : (englishStrings[key] ?? key) }

private let englishStrings: [String: String] = [
    "準備就緒": "Ready",
    "停止": "Stop",
    "複製": "Copy",
    "取消": "Cancel",
    "收起": "Dismiss",
    "快捷鍵被佔用，請在設定更改。": "Shortcut unavailable. Choose another in Settings.",
    "麥克風已中斷或發生收音錯誤；錄音已取消。": "Microphone interrupted. Recording cancelled.",
    "請先在 Orca 點選輸入位置。": "Select an input in Orca first.",
    "請先授予輔助使用權限。完成後重新按快捷鍵。": "Allow Accessibility, then try your shortcut again.",
    "無法監察焦點變更，請重新啟動 app。": "Unable to monitor focus. Restart Orcaudio.",
    "麥克風已允許；回到 Orca 再按快捷鍵。": "Microphone allowed. Return to Orca and try again.",
    "麥克風未允許，請到設定開啟。": "Allow microphone access in Settings.",
    "位置已改變 · 完成後請手動複製": "Focus changed · copy the result when ready",
    "無法確認輸入位置 · 完成後請手動複製": "Input not verified · copy the result when ready",
    "正在聆聽": "Listening",
    "找不到錄音。": "Recording not found.",
    "正在辨識": "Transcribing",
    "正在載入模型": "Loading speech model",
    "辨識失敗。": "Transcription failed.",
    "停止後 %.2f 秒 · 請檢查辨識結果": "Ready in %.2f s · review before sending",
    "結果已準備好，請按「複製」。": "Your text is ready. Select Copy.",
    "已取消，沒有貼上文字。": "Cancelled. Nothing pasted.",
    "已複製，請自行貼上。": "Copied. Paste whenever you are ready.",
    "可以繼續說話": "you can keep speaking",
    "錄音已保存，請稍候": "audio captured, please wait",
    "載入模型 %.1f 秒 · %@": "Loading %.1f s · %@",
    "✓ 模型已就緒": "✓ Model ready",
    "正在聆聽 · %.0f 秒": "Listening · %.0f s",
    "沒有收到麥克風資料，請檢查輸入裝置。": "No microphone data. Check your input device.",
    "麥克風已中斷，錄音已取消。": "Microphone disconnected. Recording cancelled.",
    "辨識逾時，請重新開始。": "Transcription timed out. Please try again.",
    "模型已就緒": "Model ready",
    "模型未載入 · 開始錄音時自動載入": "Model asleep · loads when you start",
    "停止錄音": "Stop recording",
    "開始錄音（先點選 Orca 輸入區）": "Start recording in Orca",
    "複製上次結果": "Copy last result",
    "顯示結果": "Show last result",
    "設定與權限…": "Settings…",
    "卸載記憶體中的模型": "Unload model from memory",
    "模型已卸載；下次錄音會重新載入。": "Model unloaded. It will load on your next recording.",
    "模型只存一份。刪除後不會自動重新下載；如要再用，請在設定手動下載。": "This removes the only local model copy. It will not download automatically. To restore it, download it manually in Settings.",
    "刪除模型": "Delete model",
    "模型已刪除。": "Model deleted.",
    "快捷鍵被佔用，請換一組": "Shortcut in use. Try another.",
    "跟隨系統預設": "System default",
    "已選裝置目前未連接": "Selected device is disconnected",
    "找不到輸入裝置，請重新選擇麥克風。": "Input device not found. Choose a microphone.",
    "無法開啟所選麥克風。": "Unable to open the selected microphone.",
    "收音未能啟動，請檢查麥克風權限。": "Recording could not start. Check microphone access.",
    "收音格式無效。": "Unsupported microphone format.",
    "無法讀取收音資料。": "Unable to read microphone audio.",
    "錄音不足一秒。": "Recording is shorter than one second.",
    "沒有收到清晰聲音，未貼上文字。": "No clear audio detected. Nothing pasted.",
    "輸入位置已改變，請按「複製」。": "Input changed. Select Copy to paste manually.",
    "未能複製結果，請重新按「複製」。": "Unable to copy. Please select Copy again.",
    "輸入位置已改變，結果已保留於剪貼板。": "Input changed. Your text is on the clipboard.",
    "結果已複製，請手動貼上。": "Copied. Please paste manually.",
    "已貼上，請檢查後手動送出。": "Pasted. Review your text before sending.",
    "已嘗試貼上；結果保留供複製，不會重試。": "Paste attempted. Check Orca before pasting again.",
    "自訂快捷鍵": "Custom shortcut",
    "按下新快捷鍵（Escape 取消）": "Press a shortcut (Escape to cancel)",
    "模型或 Python 環境不存在。請在專案執行 setup.sh／run download；不會自動下載。": "Model or Python environment missing. Run setup.sh / run download in the project. No automatic download.",
    "一般設定": "General",
    "語音模型": "Speech model",
    "權限": "Permissions",
    "介面語言": "App language",
    "麥克風": "Microphone",
    "快捷鍵": "Shortcut",
    "辨識語言": "Speech language",
    "自動判定（廣東話＋英文）": "Automatic (Cantonese + English)",
    "指定廣東話": "Cantonese",
    "在 Orca 說話，讓想法成為文字。": "Your voice, at home in Orca.",
    "本機辨識・由你決定何時送出": "On-device dictation. You stay in control.",
    "點擊欄位後按下新組合": "Click the field, then press a new combination",
    "在 Finder 顯示": "Show in Finder",
    "複製路徑": "Copy path",
    "已複製路徑": "Path copied",
    "存放位置": "Storage location",
    "磁碟佔用": "On disk",
    "狀態": "Status",
    "已下載・閒置中": "Downloaded · asleep",
    "未下載": "Not downloaded",
    "載入中": "Loading",
    "僅在這部 Mac 辨識，不傳送錄音。": "Audio stays on this Mac. No cloud transcription.",
    "停止後刪除錄音・閒置 10 分鐘釋放模型記憶體": "Audio deleted after processing · model sleeps after 10 min",
    "輔助使用": "Accessibility",
    "已允許": "Allowed",
    "未允許": "Not allowed",
    "允許": "Allow",
    "管理": "Manage",
    "允許麥克風": "Allow microphone",
    "開啟輔助使用設定": "Open Accessibility settings",
    "Escape 取消": "Escape to cancel",
    "結束 Orcaudio": "Quit Orcaudio",
    "刪除模型（%@）…": "Delete model (%@)…",
    "刪除本機模型（%@）？": "Delete the local model (%@)?",
    "辨識程序已結束（%d）。請重新開始。": "Speech worker exited (%d). Please try again.",
    "設定": "Settings",
    "重新整理麥克風": "Refresh microphones",
    "介面語言不影響辨識或輸出語言。": "App language does not change transcription language.",

    "隨 Orca 啟動": "Launch with Orca",
    "啟動": "Startup",
    "可下載模型": "Available downloads",
    "下載模型": "Download",
    "已下載": "Downloaded",
    "版本": "Version",
    "正在連接下載服務…": "Connecting to download service…",
    "下載中 %.2f / %.2f GB": "Downloading %.2f / %.2f GB",
    "手動下載 · 取消後可續傳 · 不自動重新下載": "Manual download · resumable · never downloads automatically",
    "下載失敗，請檢查網絡後重試。": "Download failed. Check your connection and try again.",
    "找不到啟動助手，請重新安裝 Orcaudio。": "Launch helper missing. Reinstall Orcaudio.",
    "未能啟用自動啟動，請再試一次。": "Could not enable automatic launch. Please try again.",
    "模型尚未下載。請在設定的模型下載選單下載。": "No model installed. Choose Download in Settings.",

    "GPU 記憶體（MLX）": "GPU memory (MLX)",
    "統一記憶體用量，非 GPU 運算百分比 · 每秒更新": "Unified memory, not GPU compute % · updates every second",
    "未載入 · 0 MB": "Unloaded · 0 MB",
    "使用中 %.2f GB · 快取 %.0f MB": "Active %.2f GB · cache %.0f MB",
    "等待量度…": "Waiting for measurement…",

    "正在準備收音": "Opening microphone",
    "已等待 %.1f 秒 · Escape 取消": "Waiting %.1f s · Escape to cancel",
    "請檢查文字後再送出": "Review your text before sending",
]
