import Foundation

var usesTraditionalChinese: Bool { UserDefaults.standard.string(forKey: "uiLanguage") == "zh-Hant" }

/// English is both the source text and default; only UI strings pass through here.
func L(_ english: String) -> String {
    usesTraditionalChinese ? (traditionalChineseStrings[english] ?? english) : english
}

let traditionalChineseStrings: [String: String] = [
    "Manage the current goal before switching modes.": "請先處理目前的 Goal，再切換模式。",
    "Mode switching": "切換模式",
    "⇧Tab · Cursor / Codex input": "⇧Tab · Cursor／Codex 輸入框",
    "Finish dictation before switching modes.": "請先完成聽寫，再切換模式。",
    "Mode controls unavailable. Use the app's mode menu.": "未能找到模式控制項，請使用 App 的模式選單。",
    "Mode change not confirmed. Check the app's mode menu.": "未能確認模式已切換，請檢查 App 的模式選單。",

    "Supported apps": "支援的 App",
    "Launch with enabled apps": "隨已啟用的 App 啟動",
    "ChatGPT includes Codex mode. Only chat inputs are supported.": "ChatGPT 包括 Codex 模式。僅支援聊天輸入框。",
    "Switch to an enabled app to dictate.": "請切換至已啟用的支援 App。",
    "No available chat input found.": "找不到可用的聊天輸入框。",
    "Select the chat input, then try again.": "請先點選聊天輸入框，再試一次。",
    "Return to the chat before dictating.": "請先返回聊天畫面，再開始錄音。",
    "Input changed. Try your shortcut again.": "輸入位置已改變，請重新按快捷鍵。",
    "Unable to focus the chat input. Click it and try again.": "無法聚焦聊天輸入框，請點選後再試。",
    "Microphone allowed. Return to your app and try again.": "麥克風已允許；回到支援的 App 再按快捷鍵。",
    "Start recording": "開始錄音",
    "Finding chat input": "正在尋找輸入框",
    "Paste attempted. Check the input before pasting again.": "已嘗試貼上；請檢查輸入框後才手動貼上。",

    "Ready": "準備就緒",
    "Stop": "停止",
    "Copy": "複製",
    "Cancel": "取消",
    "Dismiss": "收起",
    "Shortcut unavailable. Choose another in Settings.": "快捷鍵被佔用，請在設定更改。",
    "Microphone interrupted. Recording cancelled.": "麥克風已中斷或發生收音錯誤；錄音已取消。",
    "Select an input in Orca first.": "請先在 Orca 點選輸入位置。",
    "Allow Accessibility, then try your shortcut again.": "請先授予輔助使用權限。完成後重新按快捷鍵。",
    "Unable to monitor focus. Restart Orcaudio.": "無法監察焦點變更，請重新啟動 app。",
    "Microphone allowed. Return to Orca and try again.": "麥克風已允許；回到 Orca 再按快捷鍵。",
    "Allow microphone access in Settings.": "麥克風未允許，請到設定開啟。",
    "Focus changed · copy the result when ready": "位置已改變 · 完成後請手動複製",
    "Input not verified · copy the result when ready": "無法確認輸入位置 · 完成後請手動複製",
    "Listening": "正在聆聽",
    "Recording not found.": "找不到錄音。",
    "Transcribing": "正在辨識",
    "Loading speech model": "正在載入模型",
    "Transcription failed.": "辨識失敗。",
    "Ready in %.2f s · review before sending": "停止後 %.2f 秒 · 請檢查辨識結果",
    "Your text is ready. Select Copy.": "結果已準備好，請按「複製」。",
    "Cancelled. Nothing pasted.": "已取消，沒有貼上文字。",
    "Copied. Paste whenever you are ready.": "已複製，請自行貼上。",
    "you can keep speaking": "可以繼續說話",
    "audio captured, please wait": "錄音已保存，請稍候",
    "Loading %.1f s · %@": "載入模型 %.1f 秒 · %@",
    "✓ Model ready": "✓ 模型已就緒",
    "Listening · %.0f s": "正在聆聽 · %.0f 秒",
    "No microphone data. Check your input device.": "沒有收到麥克風資料，請檢查輸入裝置。",
    "Microphone disconnected. Recording cancelled.": "麥克風已中斷，錄音已取消。",
    "Transcription timed out. Please try again.": "辨識逾時，請重新開始。",
    "Model ready": "模型已就緒",
    "Model asleep · loads when you start": "模型未載入 · 開始錄音時自動載入",
    "Stop recording": "停止錄音",
    "Start recording in Orca": "開始錄音（先點選 Orca 輸入區）",
    "Copy last result": "複製上次結果",
    "Show last result": "顯示結果",
    "Settings…": "設定與權限…",
    "Unload model from memory": "卸載記憶體中的模型",
    "Model unloaded. It will load on your next recording.": "模型已卸載；下次錄音會重新載入。",
    "This removes the only local model copy. It will not download automatically. To restore it, download it manually in Settings.": "模型只存一份。刪除後不會自動重新下載；如要再用，請在設定手動下載。",
    "Delete model": "刪除模型",
    "Model deleted.": "模型已刪除。",
    "Shortcut in use. Try another.": "快捷鍵被佔用，請換一組",
    "System default": "跟隨系統預設",
    "Selected device is disconnected": "已選裝置目前未連接",
    "Input device not found. Choose a microphone.": "找不到輸入裝置，請重新選擇麥克風。",
    "Unable to open the selected microphone.": "無法開啟所選麥克風。",
    "Recording could not start. Check microphone access.": "收音未能啟動，請檢查麥克風權限。",
    "Unsupported microphone format.": "收音格式無效。",
    "Unable to read microphone audio.": "無法讀取收音資料。",
    "Recording is shorter than one second.": "錄音不足一秒。",
    "No clear audio detected. Nothing pasted.": "沒有收到清晰聲音，未貼上文字。",
    "Input changed. Select Copy to paste manually.": "輸入位置已改變，請按「複製」。",
    "Unable to copy. Please select Copy again.": "未能複製結果，請重新按「複製」。",
    "Input changed. Your text is on the clipboard.": "輸入位置已改變，結果已保留於剪貼板。",
    "Copied. Please paste manually.": "結果已複製，請手動貼上。",
    "Pasted. Review your text before sending.": "已貼上，請檢查後手動送出。",
    "Paste attempted. Check Orca before pasting again.": "已嘗試貼上；結果保留供複製，不會重試。",
    "Custom shortcut": "自訂快捷鍵",
    "Press a shortcut (Escape to cancel)": "按下新快捷鍵（Escape 取消）",
    "Model or Python environment missing. Run setup.sh / run download in the project. No automatic download.": "模型或 Python 環境不存在。請在專案執行 setup.sh／run download；不會自動下載。",
    "General": "一般設定",
    "Speech model": "語音模型",
    "Permissions": "權限",
    "App language": "介面語言",
    "Microphone": "麥克風",
    "Shortcut": "快捷鍵",
    "Speech language": "辨識語言",
    "Automatic (Cantonese + English)": "自動判定（廣東話＋英文）",
    "Cantonese": "指定廣東話",
    "Your voice, at home in Orca.": "在 Orca 說話，讓想法成為文字。",
    "On-device dictation. You stay in control.": "本機辨識・由你決定何時送出",
    "Click the field, then press a new combination": "點擊欄位後按下新組合",
    "Show in Finder": "在 Finder 顯示",
    "Copy path": "複製路徑",
    "Path copied": "已複製路徑",
    "Storage location": "存放位置",
    "On disk": "磁碟佔用",
    "Status": "狀態",
    "Downloaded · asleep": "已下載・閒置中",
    "Not downloaded": "未下載",
    "Loading": "載入中",
    "Audio stays on this Mac. No cloud transcription.": "僅在這部 Mac 辨識，不傳送錄音。",
    "Audio deleted after processing · model sleeps after 10 min": "停止後刪除錄音・閒置 10 分鐘釋放模型記憶體",
    "Accessibility": "輔助使用",
    "Allowed": "已允許",
    "Not allowed": "未允許",
    "Allow": "允許",
    "Manage": "管理",
    "Allow microphone": "允許麥克風",
    "Open Accessibility settings": "開啟輔助使用設定",
    "Escape to cancel": "Escape 取消",
    "Quit Orcaudio": "結束 Orcaudio",
    "Delete model (%@)…": "刪除模型（%@）…",
    "Delete the local model (%@)?": "刪除本機模型（%@）？",
    "Speech worker exited (%d). Please try again.": "辨識程序已結束（%d）。請重新開始。",
    "Settings": "設定",
    "Refresh microphones": "重新整理麥克風",
    "App language does not change transcription language.": "介面語言不影響辨識或輸出語言。",
    "Launch with Orca": "隨 Orca 啟動",
    "Startup": "啟動",
    "Available downloads": "可下載模型",
    "Download": "下載模型",
    "Downloaded": "已下載",
    "Version": "版本",
    "Connecting to download service…": "正在連接下載服務…",
    "Downloading %.2f / %.2f GB": "下載中 %.2f / %.2f GB",
    "Manual download · resumable · never downloads automatically": "手動下載 · 取消後可續傳 · 不自動重新下載",
    "Download failed. Check your connection and try again.": "下載失敗，請檢查網絡後重試。",
    "Launch helper missing. Reinstall Orcaudio.": "找不到啟動助手，請重新安裝 Orcaudio。",
    "Could not enable automatic launch. Please try again.": "未能啟用自動啟動，請再試一次。",
    "No model installed. Choose Download in Settings.": "模型尚未下載。請在設定的模型下載選單下載。",
    "GPU memory (MLX)": "GPU 記憶體（MLX）",
    "Unified memory, not GPU compute % · updates every second": "統一記憶體用量，非 GPU 運算百分比 · 每秒更新",
    "Unloaded · 0 MB": "未載入 · 0 MB",
    "Active %.2f GB · cache %.0f MB": "使用中 %.2f GB · 快取 %.0f MB",
    "Waiting for measurement…": "等待量度…",
    "Opening microphone": "正在準備收音",
    "Waiting %.1f s · Escape to cancel": "已等待 %.1f 秒 · Escape 取消",
    "Review your text before sending": "請檢查文字後再送出",
    "Unable to start recording. Check microphone access and available disk space.": "無法開始錄音，請檢查麥克風權限及可用磁碟空間。",
    "Unable to save microphone audio. Check available disk space.": "無法儲存收音資料，請檢查可用磁碟空間。",
    "Unable to delete the model. Check folder permissions.": "無法刪除模型，請檢查資料夾權限。",
    "Unable to update automatic launch. Please try again.": "無法更新自動啟動設定，請再試一次。",
    "Recording must be between 1 and 120 seconds.": "錄音長度必須介乎 1 至 120 秒。",
    "The recording contains invalid audio data.": "錄音包含無效的音訊資料。",
    "No speech was recognized. Nothing pasted.": "未能辨識語音，沒有貼上文字。",
    "The transcript exceeded the length limit. Try a shorter recording.": "辨識結果超過長度限制，請縮短錄音後再試。",
    "Transcription failed. Please try again.": "辨識失敗，請再試一次。",
    "Unable to read the recording. Please try again.": "無法讀取錄音，請再試一次。",
    "Orca input is not ready. Click the input and try your shortcut again.": "尚未能讀取 Orca 輸入位置，請點選輸入框後再按快捷鍵。",
]
